//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
namespace Moments.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Moments
    {
        public int Id { get; set; }
        public int Username { get; set; }

        [StringLength(30, MinimumLength = 1, ErrorMessage = "You have to enter a title between 1 and 30 characters")]
        [Required(ErrorMessage = "You have to enter a title")]
        public string Titel { get; set; }

        [StringLength(80, MinimumLength = 1, ErrorMessage = "You have to enter a title between 1 and 80 characters")]
        [Required(ErrorMessage = "You have to enter a title")]
        public string Description { get; set; }

        public string Image { get; set; }

        [StringLength(20, MinimumLength = 1, ErrorMessage = "You have to enter a date between 1 and 20 characters")]
        [Required(ErrorMessage = "You have to enter a date")]
        public string Date { get; set; }
        public int Place { get; set; }
    
        public virtual Login Login { get; set; }
        public virtual Place Place1 { get; set; }
    }
}
